name: pet_care
description: "no"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #* Local storage
  hive_flutter: ^1.1.0

  #* Router
  auto_route: ^10.0.1

  #* Riverpod
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  
  #* Introduction
  introduction_screen: ^3.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.4.15

  #* Dependency for router
  auto_route_generator: ^10.0.1

flutter:

  uses-material-design: true
