name: pet_care
description: "All info in the readme file"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #* Other things
  connectivity_plus: ^6.1.3
  flutter_svg: ^2.0.17
  gap: ^3.0.1

  #* Firebase
  flutterfire_cli: ^1.1.0
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  firebase_database: ^11.3.5
  # Authentication with firebase
  firebase_auth: ^5.5.2
  email_validator: ^3.0.0
  # Authentication with Google
  google_sign_in: ^6.3.0
  google_sign_in_web: ^0.12.4+4

  #! Used for contain all api's keys
  flutter_dotenv: ^5.2.1

  #* Local storage
  hive_flutter: ^1.1.0

  #* Router
  auto_route: ^10.0.1

  #* Riverpod
  flutter_riverpod: ^2.6.1

  #* Introduction
  introduction_screen: ^3.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.4.15

  #* Dependency for router
  auto_route_generator: ^10.0.1

flutter:
  uses-material-design: true

  assets:
    - .env
    # Images & icons
    - lib/logic/src/assets/imgs/logo.png
    - lib/logic/src/assets/imgs/welcome.png
    - lib/logic/src/assets/icons/icon_dog&cat.png
    - lib/logic/src/assets/icons/icon_pet_a_pet.png
    - lib/logic/src/assets/icons/icon_title_1.png
    - lib/logic/src/assets/icons/icon_title_2.png
    - lib/logic/src/assets/icons/icon_documents.png
    - lib/logic/src/assets/icons/icon_title_3.png
    - lib/logic/src/assets/icons/icon_form.png
    - lib/logic/src/assets/icons/icon_google.png
    # Fonts
    - lib/logic/src/fonts/Poppins/Poppins-Regular.ttf
    - lib/logic/src/fonts/Poppins/Poppins-Bold.ttf
    - lib/logic/src/fonts/Poppins/Poppins-Italic.ttf
    - lib/logic/src/fonts/Poppins/Poppins-Light.ttf
  
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/logic/src/fonts/Poppins/Poppins-Regular.ttf
        - asset: lib/logic/src/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: lib/logic/src/fonts/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: lib/logic/src/fonts/Poppins/Poppins-Light.ttf
          weight: 300